[package]
name = "btlescan"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11"
ratatui = "0.25"
tokio = { version = "1", features = ["full"] }
crossterm = "0.22"
futures = "0.3"
chrono = "0.4"
uuid = "1.6"
lazy_static = "1.4.0"

[target.'cfg(target_os = "linux")'.dependencies]
bluez-async = "0.7"