# From: https://github.com/marketplace/actions/rust-release-binary
on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
            pre_script: ".github/scripts/linux_dep.sh"
          - target: x86_64-apple-darwin
            archive: zip
            rust_ver: 1.74
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          PRE_BUILD: ${{ matrix.pre_script }}
          TOOLCHAIN_VERSION: ${{ matrix.rust_ver }}
          EXTRA_FILES: "README.md LICENSE"
